version: '2'

services:
  
  proxy:
    
    build: ./Proxy/
    
    ports:
      - 9956:5000
    
    depends_on:
      - server
    
    external_links:
      - server

  server:
    build: ./Server2/
